@host=http://localhost:5062

GET  {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmJlNGUzYi0xNmZlLTQ4NzUtYjk3MS00OTYwMzNiOWI1OTAiLCJnaXZlbl9uYW1lIjoiQXZlc2giLCJmYW1pbHlfbmFtZSI6IkRpbGFrc2hhIiwianRpIjoiNzBmMjQ4ZWMtYWMzZi00ZGZlLTk5YzEtYmUwODU4ZTAzOWMwIiwiZXhwIjoxNzE3NTA1MjQ4LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.jExWf0-AoG_zWV2XHjJyMAiSUJj4juDdVgjLbuRgGzc